# Generated by Django 2.2.6 on 2019-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_book_api', '0002_auto_20191029_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergy_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
