# Generated by Django 2.2.6 on 2019-10-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_book_api', '0004_auto_20191029_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='parent',
        ),
        migrations.AddField(
            model_name='home',
            name='parent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
