# Generated by Django 2.2.6 on 2019-10-30 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_book_api', '0005_auto_20191029_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='parent',
        ),
        migrations.AddField(
            model_name='home',
            name='parent',
            field=models.ManyToManyField(related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
