# Generated by Django 2.2.6 on 2019-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_book_api', '0009_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='children',
            field=models.ManyToManyField(related_name='post', to='care_book_api.Child'),
        ),
    ]
