# Generated by Django 2.2.6 on 2019-11-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_book_api', '0010_post_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name'], 'verbose_name_plural': 'allergies'},
        ),
    ]
